### PR TITLE
command RUN['chmod'] added to DockerFile to make docker work

### PR DESCRIPTION
**Pull request by annashamray**
just added one command in the end of DockerFile

### CODE REVIEW

**Comment by joeribekker** [comment]
Seems odd that the command should run **after** running `start.sh`. I prefer to just set +x permissions on `start.sh` in the repository. Can you do that instead of this?

**Comment by annashamray** [comment]
swapped these commands in DockerFile

**Comment by joeribekker** [comment]
> I prefer to just set +x permissions on start.sh in the repository. Can you do that instead of this?

Just do chmod +x locally and commit the start.sh file with updated permissions.

**Comment by annashamray** [comment]
Done. DockerFile is back to normal now. Execute permission is added to bin/docker_start.sh

**Pull request merged**
